### ISSUE TITLE
Several errors in Week1/C/palindrome.c

### ISSUE THREAD

**Issue by traktofon** [gjbex/DPD#2]
The MOOC quiz 1.16, question 12, seems to suggest that the only issues with this code are that the main function should check whether there is an argument and whether that argument contains only letters (the latter being questionable, as one might want to check for palindromic numbers).

But the `pal` function (called `is_palindrome` in the MOOC) contains several errors that render it non-functional. An IMHO correct implementation is:
```
int pal(char a[]) {
    if (strlen(a))
        if (a[0] != a[strlen(a)-1])
            return 0;
        else {
            a[strlen(a)-1] = 0;
            return pal(&(a[1]));
        }
    else
        return 1;
}
```
(I'm not submitting a PR as I'm wondering if the errors are supposed to be in there.)

Moreover, even if working as intended (?), the `pal` function will overwrite the string passed to it, so that the `printf` call in the `main` function won't print the original string. Using `pal(strdup(argv[1]))` instead of `pal(argv[1])` can fix this, though strictly one should also check that the `strdup` call succeeds.

If the errors are intended, maybe there should be an additional answer option: "Error handling is not required at this stage, as the program should first be made to work correctly."

**Comment by gjbex** [comment]
@traktofon You are perfectly right that there are issues with the code.  It is intended as a running exercise, so you will get the opportunity to fix them later on in the course.

Thanks for your feedback :)

**Comment by traktofon** [comment]
Thanks, great to know. In this case I'm closing the issue.
